env: development
spring:
  application: {name: core_demo}
eureka:
  client: {serviceUrl: 'http://47.100.233.96:8761/eureka/'}
  instance: {preferIpAddress: true,  port: '5001', statusPageUrlPath: '/api/values'}
ConnectionStrings: {MysqlConnection: mysql connection string, RedisConnection: redis connection string}
